//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUTOPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class AUTOS
    {
        
        public int IDauto { get; set; }
        [Display(Name = "Marca")]
        [Required(ErrorMessage ="La marca es requerida.")]
        public string Marca { get; set; }
        [Display(Name = "Modelo")]
        [Required(ErrorMessage = "El modelo es requerido.")]
        public string Modelo { get; set; }

        [Display(Name = "Año")]
        [Required(ErrorMessage = "El año es requerido.")]
        public string Anio { get; set; }
        [Display(Name = "Color")]
        [Required(ErrorMessage = "El color es requerido.")]
        public string Color { get; set; }

        [Display(Name = "Tipo de vehiculo")]
        [Required(ErrorMessage = "El vehiculo es requerido.")]
        public string TipoVehiculo { get; set; }

        [Display(Name = "Precio")]
        [Required(ErrorMessage = "El precio es requerido.")]
        public Nullable<double> Precio { get; set; }

        [Display(Name = "Imagen")]
        public string ImgRuta { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Estatus")]
        [Required(ErrorMessage = "El estatus es requerido.")]
        public Nullable<int> miEstatus { get; set; }

        [Display(Name = "Direccion")]
        [Required(ErrorMessage = "La direccion es necesaria.")]
        public string Direccion { get; set; }
    }
}
